name: action.yml 2025-07-13
run-name: ${{ github.actor }} is running action.yml
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
      - run: unzip images/come.zip
      - run: ls
      - run: pwd
      - run: ls /home/runner/work/actions/actions
      - run: sudo apt-get install -y imagemagick
      - run: mogrify -version
