name: action.yml 2025-07-13
run-name: ${{ github.actor }} is running action.yml
on: [push]

env:
 NODE_VERSION: lts/*
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: ls
      - run: ls huawei/jpg
      - run: ls jpg/2021
      - run: ls jpg/2025
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: node linux.js
     
